// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func About() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><h1>About</h1><p>This site is a collection of quotes I have come across, mostly about life and software development</p><p>It was inspired by <a target=\"_blank\" href=\"https://megamanquotes.com/\">Mega Man Quotes</a>, please go there for all your software development quotes</p><p>It was built using <a target=\"_blank\" href=\"https://htmx.org/\">HTMX</a>, <a target=\"_blank\" href=\"https://go.dev\">Go</a> + <a target=\"_blank\" href=\"https://templ.guide/\">Templ</a>, <a href=\"https://turso.tech/\">Turso</a>, and is hosted on <a target=\"_blank\" href=\"https://cloud.google.com/run/\">Google Cloud Run</a></p><p>It is open source and you can find the code on my <a target=\"_blank\" href=\"https://github.com/Linkinlog\">GitHub</a></p></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
